language: node_js
node_js:
- "stable"
- "lts/*"
cache:
  directories:
  - "node_modules"
branches:
  except:
  - version

script:
    - npm test
    - node ./node_modules/.bin/istanbul cover _mocha ./spec/ --async-only --exit --report lcovonly -- -R spec --exit && cat ./coverage/lcov.info | codacy-coverage --token $CODACY_PROJECT_TOKEN && rm -rf ./coverage
