version: '3.5'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:5.0
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8010:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://0.0.0.0:8010
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    volumes: ["concourse-keys:/concourse-keys"]

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - mqtt-config:/mosquitto/config
    - mqtt-data:/mosquitto/data
    - mqtt-log:/mosquitto/log

  mqtt-resource:
    build: .
    image: vergissberlin/mqtt-resource:development

volumes:
  concourse-keys:
  mqtt-config:
  mqtt-data:
  mqtt-log:
