---

#####################################################################################
resources:

# Docker
- name: docker-alpine
  type: docker-image
  source:
    repository: alpine

# Others
- name: mqtt-broker
  type: mqtt-resource
  source:
    url: mqtt://test.mosquitto.org
    port: 1883
    topic: test

#####################################################################################
resource_types:

- name: mqtt-resource
  type: docker-image
  source:
    repository: vergissberlin/mqtt-resource
    tag: development


#####################################################################################
jobs:

- name: test
  serial: true
  plan:
  - aggregate:
    - get: docker-alpine
      trigger: true
    - get: mqtt-broker
      trigger: true
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: docker-alpine
      outputs:
      - name: out
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Hello World"
  on_success:
    put: mqtt-broker
    params:
      payload: Release success
      topic: test
  on_failure:
    put: mqtt-broker
    params:
      payload: Release failure
      topic: test
  on_abort:
    put: mqtt-broker
    params:
      payload: Release aborted
      topic: test
